import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Tag from '@/components/Tag/Tag';
import withLayout from '@/Layout/Layout';


 function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fox.ico" />
      </Head>
      <main className={styles.main}>
        <Tag tag={'h1'}>Hello world!</Tag>
      </main>
    </div>
  )
}

export default withLayout(Home);
